(() => {
  const mount=document.getElementById('vf-en-tail-root');if(!mount)return;
  const asset=name=>new URL(`../assets/remaining/${name}`,document.baseURI).href;
  const reviews=[
    ['Evgeniy Kolosov','Vetratoria in Egypt left me with nothing but positive impressions. High level of professionalism from the instructors, ideal conditions, and a very friendly atmosphere.','review-01.webp'],
    ['Yuriy Tolchinskiy','Was here in August to master wing foiling. I was able to fly on the foil and make turns quite quickly. Thanks to Hassan for the productive training sessions.','review-02.webp'],
    ['Boris Sizov','Very convenient. It’s my second time coming without gear, and they have all sizes of wings and boards. There’s always enough equipment. Tolya, Irina, and Hassan are true professionals who know their stuff.','review-03.webp'],
    ['Dmitrii Polishchuk','An amazing surf station! Great location for heading out to sea. Friendly staff! Excellent equipment for wing foiling, highly recommended to everyone!','review-04.webp'],
    ['Olga Krasnova','Wing Center Vetratoria is a magical place! My first steps on a wing foil were a success. The guys have top-notch gear. Suitable for both beginners and advanced wingers.','review-05.webp']
  ];
  mount.innerHTML=`
    <section class="remain-record remain-form-record"><div class="remain-form"><div class="remain-form__image"><img src="${asset('form.webp')}" loading="lazy" decoding="async" alt="Wingfoil Dahab"></div><form><div class="remain-success">Thank you! We will contact you soon via WhatsApp or Telegram.</div><label>Name / Convenient time to contact / Other questions<input name="name" placeholder="Name, Saturday at 4:00 p.m."></label><label>Your email<input type="email" name="email" required placeholder="vetratoria@wingfoildahab.com"></label><fieldset><legend>Choose a convenient method of communication</legend><div class="remain-methods"><label><input type="radio" name="method" value="whatsapp" checked> WhatsApp</label><label><input type="radio" name="method" value="telegram"> Telegram</label></div><input name="contact" required placeholder="Phone number or username"></fieldset><button class="remain-submit">Send</button></form></div></section>
    <section class="remain-record remain-reviews-record"><div class="remain-reviews"><div class="remain-container"><h2>What Our Guests Say</h2><p class="remain-reviews-sub">More reviews can be found <a target="_blank" rel="noopener" href="https://www.tripadvisor.com/Attraction_Review-g297547-d15082101-Reviews-Vetratoria_Windsurfing_Wingfoil_Center-Dahab_South_Sinai_Red_Sea_and_Sinai.html">HERE</a></p><button class="remain-review-nav remain-review-prev" type="button" aria-label="Previous review">❮</button><button class="remain-review-nav remain-review-next" type="button" aria-label="Next review">❯</button><div class="remain-review-viewport"><div class="remain-review-track">${reviews.map(review=>`<article class="remain-review-card"><div class="remain-review-user"><img src="${asset(review[2])}" loading="lazy" decoding="async" alt="${review[0]}"><b>${review[0]}</b></div><p>${review[1]}</p></article>`).join('')}</div></div></div></div></section>
    <section class="remain-record remain-directions-record"><div class="remain-directions"><div class="remain-container"><div class="remain-directions-image"><img src="${asset('directions.webp')}" loading="lazy" decoding="async" alt="Dahab"></div><div class="remain-directions-copy"><h2>How to Get Here?</h2><div class="remain-title-line"></div><p>Dahab is located on the coast of the Gulf of Aqaba in the Red Sea, South Sinai. It is only 100 km from Sharm El Sheikh, where the nearest international airport is located.</p><p>You can also travel conveniently via Istanbul. The transfer from Sharm El Sheikh airport to Dahab takes about one hour.</p><div class="remain-highlight">We can arrange your transfer!<br>Transfer for station guests — $30</div><a class="remain-transfer" href="#vf-en-contact-root">Book a transfer</a><h3>Entry and visa requirements</h3><ul><li>Your passport must be valid for at least six months from the date of entry.</li><li>For stays of up to 14 days in Sinai, you can receive a free Sinai Only stamp.</li><li>For travel elsewhere in Egypt or stays longer than two weeks, a tourist visa is required ($25).</li></ul></div></div></div></section>`;
  let index=0;
  const track=mount.querySelector('.remain-review-track');
  const move=direction=>{index=(index+direction+reviews.length)%reviews.length;track.style.transform=`translateX(-${index*50}%)`};
  mount.querySelector('.remain-review-prev').addEventListener('click',()=>move(-1));
  mount.querySelector('.remain-review-next').addEventListener('click',()=>move(1));
  mount.querySelector('.remain-form form').addEventListener('submit',event=>{event.preventDefault();mount.querySelector('.remain-success').classList.add('active')});
})();
