(() => {
  const translations = new Map([
    ['Обучение','Lessons'],['Снаряжение','Equipment'],['Прогноз','Forecast'],['Команда','Team'],['ЧЗВ','FAQ'],['Организаторам','For organizers'],['Виндсерфинг','Windsurfing'],['РУС','RU'],
    ['Вингфойлинг – термин, используемый Всероссийской Федерацией Парусного Спорта в соответствие с представленным ВФПС переводом международных правил по вингфойлингу класс – доска с крылом (Всероссийский реестр видов спорта) международное название WingFoil','Wingfoiling is a modern sailing discipline where the rider uses a handheld inflatable wing and a hydrofoil board. Its international name is WingFoil.'],
    ['Обучение парусному спорту.','Sailing sport lessons.'],['Класс: Доска с крылом – ','Class: Wing board — '],['вингфойлинг','wingfoiling'],['Идеальное место для катания круглый год!','The perfect place to ride all year round!'],
    ['Откройте для себя водный спорт в лучшей акватории мира!','Discover water sports at one of the world’s best spots!'],['- Безопасное обучение','- Safe lessons'],['- Идеальные ветровые условия','- Ideal wind conditions'],['- Профессиональное оборудование','- Professional equipment'],['- Опытные инструктора','- Experienced instructors'],['Этапы обучения','Training stages'],['Пакеты обучения','Training packages'],['Прокат снаряжения','Equipment rental'],['Контакты','Contacts'],['Закрыть','Close'],['Связаться с нами','Contact us'],
    ['★★★★★ "Лучшая станция вингфойла в Дахаб." 17 сентября 2024 - Путешественник Tripadvisor Прочитать 144 отзывов о Vetratoria Windsurfing & SUP ★★★★★','★★★★★ “The best wingfoil center in Dahab.” September 17, 2024 — Tripadvisor traveler. Read 144 reviews of Vetratoria Windsurfing & SUP ★★★★★'],
    ['Мы находимся в ','We are located in '],['Дахабе.','Dahab.'],['Дахаб — уникальное место ветров, столица водных видов спорта. Это небольшой и красивый курортный город, расположенный ','Dahab is a unique windy destination and a capital of water sports. It is a small, beautiful resort town located '],['в часе езды от аэропорта Шарм-эль-Шейх, Египет.','one hour from Sharm El Sheikh Airport, Egypt.'],
    ['Наша станция «Ветратория» — школа и спортивный клуб, где вы откроете для себя мир нового водного вида спорта, освоите новые умения и расширите свои навыки. Вы сможете насладиться идеальными условиями для катания: стабильным ветром независимо от сезона, гладкой водой ','Vetratoria is a school and sports club where you can discover a new water sport, learn new skills and progress confidently. Enjoy ideal riding conditions: reliable wind in every season, flat water '],['в закрытой Лагуне','inside the sheltered Lagoon'],['продуваемой Скоростной зоне','windier Speed Zone'],['волнами в зоне открытого моря','waves in the open-sea zone'],[' и более ',' and the '],[', а также размеренными ',', plus gentle '],[', тёплым солнцем и дружелюбной атмосферой.',', warm sunshine and a friendly atmosphere.'],
    ['У нас три спасательных катера, и мы предоставляем спасательный телефон для выходов на волны в зону открытого моря.','We have three rescue boats and provide a safety phone for riders heading to the open-sea wave zone.'],['В вашем распоряжении новейшее оборудование и широкий выбор досок, вингов и подводных крыльев от известнейшей итальянской компании ','You will have access to the latest equipment and a wide selection of boards, wings and hydrofoils from the renowned Italian brand '],
    ['Наша станция «Ветратория» – первый официально лицензированная станция вингфойлинга в Египте, Синай.','Vetratoria is the first officially licensed wingfoil center in Sinai, Egypt.'],['Мы также являемся официальным тест-центром оборудования ','We are also an official equipment test center for '],['Откройте для себя мир нового водного спорта, ощутите непередаваемое ','Discover a new world of water sports, experience the unforgettable '],['чувство полета и зарядитесь яркими эмоциями в лучшем ветровом споте – Дахаб, вместе с нашей станцией!','feeling of flight and enjoy the energy of Dahab’s outstanding wind spot with our team!'],['Наша акватория','Our spot'],
    ['Наша ','Our '],['акватория','riding area'],['Дахаб — идеальное место для всех, от новичков до опытных райдеров. Чистота и отсутствие мусора делают катание на фойле максимально комфортным!','Dahab is ideal for everyone, from complete beginners to experienced riders. Clean water and a clear riding area make foiling especially comfortable.'],['01. ЛАГУНА','01. LAGOON'],['Идеально для начинающих. Песчаная коса обеспечивает полную безопасность, а ровная вода и обширные отмели — лучший старт для первых «полетов».','Perfect for beginners. A sandy spit keeps the area sheltered, while flat water and wide shallows create the best conditions for first flights.'],['02. СКОРОСТНАЯ ЗОНА','02. SPEED ZONE'],['Зона с самым стабильным ветром для скоростного катания. Ровная вода переходит в чоп, а безопасность обеспечивает постоянное наблюдение и «спасательный остров».','The area with the most consistent wind for fast riding. Flat water gradually turns into chop, with constant supervision and a safety island.'],['03. ВОЛНОВАЯ ЗОНА','03. WAVE ZONE'],['Открытое море за рифом с пологими волнами до 3 м. Идеально для вейв-фойлинга и прыжков. Для полной безопасности выдаем спасательные телефоны.','Open sea beyond the reef with smooth waves up to 3 m. Ideal for wave foiling and jumps. We provide safety phones for additional protection.'],['Вид со спутника','Satellite view'],['Карта спота','Spot map'],['Спутник','Satellite'],['Карта акватории','Riding area map'],
    ['Анатолий','Anatoly'],['Хасан','Hasan'],['Егор','Egor'],['Рома','Roma'],['Ира','Ira'],['Анна','Anna'],['Менеджер станции и старший инструктор','Center manager and senior instructor'],['Профессиональный инструктор','Professional instructor'],['Детский спортивный инструктор','Children’s sports instructor'],['Инструктор','Instructor'],['Администратор','Administrator'],['Языки:','Languages:'],['Русский, Немецкий, Английский','Russian, German, English'],['Русский, Английский','Russian, English'],['Русский','Russian'],
    ['Опыт в водных видах спорта более 25 лет. Подберет идеально подходящий комплект RRD под ваши навыки и условия, обеспечив легкость и прогресс на занятиях.','Over 25 years of experience in water sports. He will select the ideal RRD setup for your level and conditions to make every lesson comfortable and productive.'],['Самый узнаваемый райдер спота с 10-летним опытом. Его позитивный настрой и индивидуальный подход помогут вам быстро обрести уверенность на крыле и насладиться полетом.','One of the spot’s best-known riders, with 10 years of experience. His positive attitude and personal approach will help you gain confidence and enjoy flying.'],['Тренирует детей от 8 лет. Превращает обучение в увлекательную игру, закладывая профессиональную базу знаний и прививая любовь к водному спорту.','Teaches children from age eight. He turns learning into an engaging game while building solid technique and a love of water sports.'],['Мастер простых объяснений сложной физики ветра. Разберет ошибки, покажет правильную технику и научит вас самостоятельно определять направления для катания.','A master at explaining wind physics in simple terms. He identifies mistakes, demonstrates proper technique and teaches you to choose riding directions independently.'],['Душа станции. Отвечает за уют, безопасность на воде и ваше отличное настроение. Всегда готова сварить кофе и поддержать дружескую беседу.','The heart of the center. She takes care of comfort, water safety and your good mood, and is always ready to make coffee and have a friendly chat.'],['Простым языком заложит уверенный фундамент навыков для вашего прогресса. Создает вдохновляющую атмосферу, в которой обучение приносит одно удовольствие.','She builds a strong foundation in clear, simple language and creates an inspiring atmosphere where learning is genuinely enjoyable.'],['В нашей школе работают опытные инструктора, которые уже научили вингфойлингу 1500+ людей!','Our experienced instructors have already taught more than 1,500 people to wingfoil!'],['Записаться на урок','Book a lesson'],
    ['Инструктор с лодкой','Instructor with a boat'],['Используем лодку во время уроков. Начнем занятие в наиболее подходящей ветровой части акватории для вашего комфорта.','We use a boat during lessons and start in the part of the riding area with the best wind for your comfort.'],['Рации с микрофоном','Radio communication'],["Мы используем BB-Talkin' для легкой связи с инструктором в режиме реального времени. Вы слышите советы прямо во время движения.","We use BB-Talkin’ headsets for easy real-time communication, so you hear your instructor’s advice while riding."],['Практика на воде','On-water practice'],['Под чутким наблюдением вы сможете легко освоить вингфойлинг. За вашей безопасностью присматривают 3 спасательные лодки.','You will learn wingfoiling under close supervision, with three rescue boats looking after your safety.'],['Час проката в подарок','One free rental hour'],['После первого урока вы получите комплект «Доска с швертом + надувное крыло» на 1 час проката совершенно бесплатно.','After your first lesson, you receive one free hour with a daggerboard board and inflatable wing.'],['Мы научим вас ','We will teach you to '],['летать!','fly!'],['Написать нам','Message us'],
    ['Вингфойлинг станция','Wingfoil center'],['Процесс ','Training '],['обучения','process'],['Мы можем организовать профессиональную фото или видео съемку во время вашего урока','We can arrange a professional photo or video shoot during your lesson.'],
    ['Ваш путь к ','Your path to your '],['первому полету','first flight'],['Подробнее →','Learn more →'],['1 этап','Stage 1'],['2 этап','Stage 2'],['3 этап','Stage 3'],['4 этап','Stage 4'],['Швертовая доска + винг','Daggerboard + wing'],['Фойл + Лодка','Foil + boat'],['Вингфойлинг (Полет)','Wingfoiling (flight)'],['Повороты и Элементы','Turns and maneuvers'],['Учимся управлять крылом на стабильной доске без фойла.','Learn wing control on a stable board without a foil.'],['Отработка баланса и взлета на гидрофойле за катером.','Practice balance and takeoff on a hydrofoil behind a boat.'],['Соединяем крыло и фойл для полноценного полета.','Combine wing and foil for a complete flight.'],['Джайбы, оверштаки и основы катания на волнах.','Jibes, tacks and the basics of wave riding.'],['Записаться на обучение','Book training'],['Забронировать этот этап','Book this stage'],
    ['На этом уроке вы научитесь управлять парусом на швертовой доске без подводного крыла. Это база, необходимая для понимания тяги ветра.','In this lesson you learn to control the wing on a daggerboard board without a hydrofoil—the essential foundation for understanding wind power.'],['Удержание паруса и контроль угла','Wing handling and angle control'],['Управление скоростью и тягой','Speed and power control'],['Повороты и движение на ветер','Turning and riding upwind'],['Возврат к станции','Returning to the center'],['Цель: Разобрать технику управления парусом. Обычно достаточно 1-2 занятий.','Goal: understand wing-control technique. Usually one or two lessons are enough.'],['Осваиваем управление доской с подводным крылом, держась за фал буксирующей лодки. Это исключает влияние ветра и позволяет сфокусироваться на балансе.','Learn to control a hydrofoil board while holding a tow rope behind a boat, removing the wind factor so you can focus on balance.'],['Выход на подводное крыло','Hydrofoil takeoff'],['Контроль высоты полета','Flight-height control'],['Чувство стабильности и управления доской','Board stability and control'],['Цель: Контроль высоты взлета. Обычно хватает 30-90 минут за лодкой.','Goal: control your flying height. Usually 30–90 minutes behind the boat is enough.'],['Объединяем все навыки: доска с подводным крылом под ногами и ветер в руках. Это момент вашего первого настоящего полета.','Bring all the skills together: a hydrofoil under your feet and the wind in your hands. This is your first true flight.'],['Выход на крыло с помощью винга','Taking off with the wing'],['Контроль высоты и стабильный полет','Height control and stable flight'],['Разгон и управление скоростью','Acceleration and speed control'],['Возвращение в точку старта','Returning to your starting point'],['Для стабильного полета требуется 1–3 занятия с последующей практикой.','Stable flight usually takes one to three lessons followed by practice.'],['Если вы уже уверенно летаете, пора учиться делать это красиво и без остановок. Маневры и первые выходы на волны.','Once you fly confidently, it is time to ride smoothly without stopping, learn maneuvers and make your first wave sessions.'],['Повороты фордевинд и оверштак','Jibes and tacks'],['Движение без потери высоты','Riding without losing ground'],['Техника старта и катания на волнах','Starting and wave-riding technique'],['Цель: Повороты на крыле без потери скорости и выход в открытое море.','Goal: foil turns without losing speed and safe riding in the open sea.'],
    ['Разовые занятия и прокат','Single lessons and rentals'],['Цены','Prices'],['Индивидуальный урок','Private lesson'],['Занятие / 1 час','Lesson / 1 hour'],['Выход в волны','Wave session'],['Для продвинутых / 1 час','Advanced / 1 hour'],['Групповой урок','Group lesson'],['2 человека / 1 час','2 people / 1 hour'],['$/чел','$/person'],['Прокат / 1 час','Rental / 1 hour'],['Урок за лодкой','Boat lesson'],['Обучение / 30 мин','Training / 30 min'],['Прокат комплекта','Full-set rental'],['Full Set / 1 час','Full set / 1 hour'],['Записаться','Book now'],['Подробнее','Details'],['В стоимость урока включено: оборудование, страховка, шлем и жилет.','Lesson price includes equipment, insurance, helmet and impact vest.'],['Цены на прокат оборудования','Equipment rental prices'],
    ['Интенсивная тренировка 1 на 1 с инструктором. Включено всё необходимое: оборудование RRD, шлем с радиосвязью для мгновенных советов и гидрокостюм. Идеально для быстрого прогресса.','Intensive one-to-one training with an instructor. Includes RRD equipment, a radio helmet for instant feedback and a wetsuit—ideal for fast progress.'],['Выход на рифовую волну Дахаба. Инструктор покажет лучшие точки и научит технике карвинга и скольжения по волне без использования тяги винга.','Ride Dahab’s reef waves. Your instructor will show you the best lines and teach carving and gliding on a wave without wing power.'],['Цена указана за одного человека. Отличный вариант для пар или друзей одного уровня. Учитесь вместе и делитесь впечатлениями от первых полетов.','Price per person. A great choice for couples or friends at the same level—learn together and share your first flights.'],['Специальный комплект для новичков. Большая доска со швертом и стабильный винг. Идеально для отработки управления крылом перед переходом на фойл.','A beginner-friendly setup with a large daggerboard board and stable wing, perfect for wing-control practice before moving to a foil.'],['Самый быстрый способ почувствовать полет. Не нужен ветер — только тяга катера. 30 минут за лодкой экономят часы самостоятельных попыток с крылом.','The fastest way to experience flight. No wind is needed—only boat power. Thirty minutes behind the boat can save hours of trial and error.'],['Премиальное оборудование RRD: карбоновые фойлы, легкие винги и современные доски. Включает сервис спасения и страховку оборудования.','Premium RRD equipment: carbon foils, lightweight wings and modern boards. Rescue service and equipment insurance are included.'],
    ['3 дня','3 days'],['4 дня','4 days'],['5 дней','5 days'],['6 дней','6 days'],['7 дней','7 days'],['1 день','1 day'],['Старт','Start'],['Базовый+','Foundation+'],['Популярный','Popular'],['Прогресс','Progress'],['Максимум','Maximum'],['Пробный','Trial'],['Интенсив','Intensive'],['Оптимальный','Optimal'],['Уверенный','Confidence'],['Мастер','Master'],['Профи','Pro'],['3 часа с инструктором','3 hours with an instructor'],['4 часа с инструктором','4 hours with an instructor'],['5 часов с инструктором','5 hours with an instructor'],['6 часов с инструктором','6 hours with an instructor'],['7 часов с инструктором','7 hours with an instructor'],['1 час с инструктором','1 hour with an instructor'],['45 мин катер + фойл','45 min boat + foil'],['60 мин катер + фойл','60 min boat + foil'],['15 мин катер + фойл','15 min boat + foil'],['Оборудование включено','Equipment included'],['Прокат SUP + Wing на день','SUP + wing rental for the day'],['Прокат весь день','All-day rental'],['Страховка + Спасение','Insurance + rescue'],['Пакеты ','Training '],['Только уроки','Lessons only'],['Интенсив (+ Прокат)','Intensive (+ rental)'],['Профессиональный курс обучения на нашей станции в Дахабе. Мы предоставляем современное оборудование RRD и услуги сертифицированных инструкторов.','A professional training course at our center in Dahab with modern RRD equipment and certified instructors.'],['Забронировать','Book now'],['Курс: ','Course: '],['Экономия: $','Save: $'],['Выбрать','Choose'],['Детали','Details'],
    ['К нам приезжают гости, а уезжают друзья!','Guests arrive and friends leave!'],['Вступить в наш телеграм чат','Join our Telegram chat'],['Связаться с нами','Contact us'],['Вы можете оставить заявку для обратной связи в удобное для Вас время.','Leave a request and we will contact you at a convenient time.'],['Или ','Or '],['напишите нам напрямую','message us directly'],[' через социальные сети.',' on social media.'],['Наши контакты','Our contacts'],['Египет, Дахаб, Ветратория.','Egypt, Dahab, Vetratoria.'],['На территории отеля SWISS INN Resort.','Located at Swiss Inn Resort.'],['Понятно','Got it'],
    ['Спасибо! С вами скоро свяжутся в WhatsApp или Telegram','Thank you! We will contact you soon via WhatsApp or Telegram.'],['Имя / Удобное время для связи / Другие вопросы','Name / Best time to contact you / Questions'],['ФИО, в субботу в 16:00','Your name, Saturday at 4 pm'],['Почта','Email'],['Выберите удобный способ связи','Choose your preferred contact method'],['Телефон или имя пользователя','Phone number or username'],['Отправить','Send'],['Отзывы наших гостей','Guest reviews'],['Больше отзывов вы можете найти ','Find more reviews '],['ЗДЕСЬ','HERE'],['Как добраться?','How to get here'],
    ['Дахаб находится на побережье Акабского залива Красного моря, Южный Синай. Всего в 100 км от Шарм-эль-Шейха, где расположен ближайший международный аэропорт.','Dahab lies on the Gulf of Aqaba on the Red Sea coast in South Sinai, only 100 km from Sharm El Sheikh and its international airport.'],['Также удобно добраться через Стамбул. Из Шарм-эль-Шейха в Дахаб трансфер занимает около часа.','Connections through Istanbul are also convenient. The transfer from Sharm El Sheikh to Dahab takes about one hour.'],['Мы можем организовать трансфер для Вас!','We can arrange your transfer!'],['Трансфер для гостей станции — $30','Transfer for center guests — $30'],['Заказать трансфер','Book a transfer'],['Правила въезда и виза','Entry and visa information'],['Паспорт должен быть действителен минимум 6 месяцев с даты въезда.','Your passport must be valid for at least six months from your arrival date.'],['До 14 дней на Синае можно бесплатно получить «Синайский штамп».','For stays of up to 14 days in Sinai, you can receive a free Sinai Only stamp.'],['Для поездок по Египту или пребывания более двух недель потребуется туристическая виза ($25).','For travel elsewhere in Egypt or stays longer than two weeks, a $25 tourist visa is required.'],
    ['ГДЕ ОСТАНОВИТЬСЯ?','WHERE TO STAY'],['ЛУЧШИЕ ОТЕЛИ В ЛАГУНЕ ДАХАБА ДЛЯ ВИНГФОЙЛИНГА','THE BEST HOTELS IN DAHAB LAGOON FOR WINGFOILING'],['Забронировать','Book now'],['Частые ','Frequently asked '],['вопросы','questions'],['Какие вещи ','What should I '],['взять с собой','bring'],['Гидрокостюм:','Wetsuit:'],['плотно прилегающий, не сковывающий движений.','a close fit that does not restrict movement.'],['Гидротапки:','Water shoes:'],['защитят от камней и обеспечат комфорт.','for protection and comfort.'],['Перчатки:','Gloves:'],['уберегут руки от натираний.','to prevent rubbing.'],['Купальник/плавки, головной убор и солнцезащитный крем.','Swimwear, a hat and sunscreen.'],['Где можно ','Where can I '],['поесть и отдохнуть','eat and relax'],['В Дахабе множество ресторанов. Можно поесть в пляжном баре рядом со станцией или заказать доставку.','Dahab has many restaurants. You can eat at the beach bar near the center or order delivery.'],['Есть ли ','Are there any '],['ограничения','restrictions'],['Обучение подходит всем в возрасте от 10 до 60+ лет. Главное — желание учиться и базовый уровень физической активности.','Training is suitable for ages 10 to 60+. All you need is motivation and a basic level of physical activity.'],['Можно ли ','Can I '],['брать семью','bring my family'],['Конечно! В Дахабе есть чистые пляжи, экскурсии, кафе и детские клубы.','Of course. Dahab offers clean beaches, excursions, cafés and children’s clubs.'],['Другие ','What other '],['активности','activities are available'],['Снорклинг и дайвинг.','Snorkeling and diving.'],['Хайкинг и прогулки в пустыне.','Hiking and desert trips.'],['Квадроциклы и верблюды.','Quad bikes and camel rides.'],['Сколько ','How much '],['времени нужно','time does it take'],[', чтобы научиться?', ' to learn?'],['За 3–5 дней вы освоите основы управления вингом. Для уверенного полета на фойле обычно требуется около недели.','You can learn basic wing control in 3–5 days. Confident foil flight usually takes around one week.'],['Какие ','What are the '],['погодные условия','weather conditions'],['Дахаб славится стабильным ветром и солнцем круглый год. Температура воздуха 25–30°C, воды — 22–26°C.','Dahab is known for reliable wind and year-round sunshine. Air temperatures are 25–30°C and water temperatures 22–26°C.'],
    ['Основной процесс обучения','Main training process'],['Вингфойл Видео 1','Wingfoil video 1'],['Вингфойл Видео 2','Wingfoil video 2'],['Вингфойл Видео 3','Wingfoil video 3'],
    ['Вингфойлинг в Дахабе','Wingfoiling in Dahab'],['Станция Ветратория','Vetratoria center'],['Катание на вингфойле','Wingfoil riding'],['Вингфойлер в Дахабе','Wingfoil rider in Dahab'],['Предыдущая фотография','Previous photo'],['Следующая фотография','Next photo'],['Гости Ветратории — фото ','Vetratoria guests — photo '],['Фото ','Photo '],['Предыдущий слайд','Previous slide'],['Следующий слайд','Next slide'],['Фотографии станции','Center photos'],[' из ',' of '],['Открыть меню','Open menu'],['Ветратория','Vetratoria'],
    ['Евгений Колосов','Evgeny Kolosov'],['Юрий Толчинский','Yuri Tolchinsky'],['Борис Сизов','Boris Sizov'],['Ольга Краснова','Olga Krasnova'],
    ['Ветратория в Египте оставила исключительно положительные впечатления. Высокий уровень профессионализма инструкторов, идеальные условия для водных видов спорта и очень дружелюбная атмосфера.','Vetratoria in Egypt made an excellent impression: highly professional instructors, ideal water-sports conditions and a very friendly atmosphere.'],['Был в августе, осваивал винг-фойл. Достаточно быстро смог летать на крыле и поворачивать. Спасибо Хасану за продуктивные тренировки!','I visited in August to learn wingfoil and quickly managed to fly and turn. Thank you, Hasan, for the productive training!'],['Очень удобно. Второй раз приезжаю без снаряги, есть все размеры крыльев и досок. Хватает всегда снаряги. Толя, Ирина и Хасан — четкие профессионалы своего дела.','Very convenient. This is my second visit without my own gear; every wing and board size is available. Anatoly, Irina and Hasan are true professionals.'],['Очень классная серф-станция! Очень удобное расположение для выхода в море. Приятный персонал! Классное оборудование для винг-фойла, всем рекомендую!','A fantastic surf center with easy access to the water, friendly staff and excellent wingfoil equipment. Highly recommended!'],['Wing Center Vetratoria — волшебное место! Первые шаги на вингфойле прошли успешно. Спасибо всей команде за теплую атмосферу!','Wing Center Vetratoria is a magical place. My first wingfoil steps were a success—thank you to the whole team for the warm atmosphere!'],
    ['Swiss Inn Resort Dahab — 4-звездочный курорт с частным пляжем на Красном море, бассейном, ресторанами и дайвинг-центром. Просторные номера с балконами предлагают виды на море или сад. На территории — спа, тренажерный зал, детский клуб и возможности для сафари. Парам особенно нравится — рейтинг 9,2.','Swiss Inn Resort Dahab is a four-star Red Sea resort with a private beach, pool, restaurants and a diving center. Spacious balcony rooms overlook the sea or garden. Facilities include a spa, gym, kids’ club and safari activities.'],['Canyon Dahab Lagona — уютный 3-звездочный отель на первой линии в Дахабе. В номерах — кондиционер, бесплатный Wi-Fi и собственная ванная комната. К услугам гостей ресторан, круглосуточная стойка регистрации и завтрак «шведский стол».','Canyon Dahab Lagona is a welcoming three-star beachfront hotel. Rooms offer air conditioning, free Wi-Fi and private bathrooms, with a restaurant, 24-hour reception and buffet breakfast.'],['Jaz Dahabeya — роскошный 4-звездочный отель с потрясающим видом на Красное море и гору Синай. К услугам гостей бассейн, сауна, спа-процедуры, тренажерный зал и разнообразные водные развлечения.','Jaz Dahabeya is a luxurious four-star hotel with views of the Red Sea and Sinai mountains, plus a pool, sauna, spa treatments, gym and a range of water activities.'],['Ganet Sinai — уютный 3-звездочный курорт с частным пляжем в районе лагуны Дахаба. К услугам гостей номера с балконами, 2 бассейна, 4 ресторана, спа и водные виды спорта.','Ganet Sinai is a friendly three-star resort with a private beach in Dahab Lagoon, balcony rooms, two pools, four restaurants, a spa and water sports.'],['Tirana Dahab — 4-звездочный курорт с 650-метровым песчаным пляжем на Красном море, в 3 км от центра Дахаба. Гостей ждут бассейн, современные номера, рестораны, бары и спа-услуги.','Tirana Dahab is a four-star resort with a 650-meter sandy Red Sea beach, 3 km from central Dahab, offering a pool, modern rooms, restaurants, bars and spa services.'],
    ['Какие погодные условия в Дахабе?','What are the weather conditions in Dahab?'],[' в Дахабе?',' in Dahab?'],['Дахаб','Dahab'],['Wingfoil Center Vetratoria на карте','Wingfoil Center Vetratoria on the map'],['Прочитать 144 отзыва о Vetratoria Windsurfing & SUP на Tripadvisor','Read 144 reviews of Vetratoria Windsurfing & SUP on Tripadvisor'],
    ['Наши контакты','Our contacts'],['Египет, Дахаб, Ветратория.','Egypt, Dahab, Vetratoria.'],['Мы находимся на территории отеля SWISS INN.','We are located at Swiss Inn Resort.'],['Прогноз ветра Дахаб','Dahab wind forecast'],['Сайт разработал: Егор Гецевич','Website by Egor Getsevich'],['Социальные сети','Social media'],['Инстаграм','Instagram'],['Телеграм','Telegram'],['Ватсап/Телеграм','WhatsApp/Telegram']
  ]);

  const translateText = value => {
    let result = value;
    [...translations].sort((a,b) => b[0].length - a[0].length).forEach(([from,to]) => { result = result.split(from).join(to); });
    return result;
  };
  const translateNode = root => {
    if (root.nodeType === Node.TEXT_NODE) { root.nodeValue = translateText(root.nodeValue); return; }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) return;
    if (root.nodeType === Node.ELEMENT_NODE) {
      ['alt','title','aria-label','placeholder'].forEach(name => { if (root.hasAttribute(name)) root.setAttribute(name, translateText(root.getAttribute(name))); });
    }
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
    let node; while ((node = walker.nextNode())) {
      if (node.nodeType === Node.TEXT_NODE) node.nodeValue = translateText(node.nodeValue);
      else ['alt','title','aria-label','placeholder'].forEach(name => { if (node.hasAttribute(name)) node.setAttribute(name, translateText(node.getAttribute(name))); });
    }
  };
  translateNode(document.body);
  const root = new URL('../', location.href);
  document.querySelectorAll('.vf-lang-btn').forEach(link => {
    const english = link.textContent.trim() === 'EN';
    link.classList.toggle('active', english);
    link.href = english ? new URL('en/', root) : new URL('clean/', root);
  });
  document.querySelectorAll('.vf-desk-logo').forEach(link => { link.href = new URL('en/', root); });
  document.querySelectorAll('a').forEach(link => {
    if (link.href.includes('/equipment-ru/')) link.href = new URL('equipment/', root);
    if (link.href.includes('/organizers-ru')) link.href = 'https://wingfoildahab.com/organizers';
    if (link.href === 'https://vetratoria.ru/ru' || link.href === 'https://vetratoria.ru/ru/') link.href = 'https://vetratoria.ru/';
  });
  const wind = document.querySelector('.remain-wind iframe');
  if (wind) wind.src = wind.src.replace('lng=ru', 'lng=en');
  const observer = new MutationObserver(records => records.forEach(record => {
    record.addedNodes.forEach(translateNode);
    if (record.type === 'characterData') translateNode(record.target);
  }));
  observer.observe(document.body, {subtree:true, childList:true, characterData:true});
})();
