(() => {
  const mount=document.getElementById('vf-guest-gallery-root'); if(!mount)return;
  const files=['gallery-01.webp','gallery-02.webp','gallery-03.webp','gallery-04.webp','gallery-05.webp','gallery-06.webp','gallery-07.webp','gallery-08.webp','gallery-09.webp','gallery-10.webp','gallery-11.webp','gallery-12.webp','gallery-13.webp'];
  const asset=name=>new URL(`../assets/gallery/${name}`,document.baseURI).href;
  mount.innerHTML=`<section class="guest-gallery"><div class="guest-viewport"><button class="guest-nav guest-prev" type="button" aria-label="Предыдущая фотография">‹</button><button class="guest-nav guest-next" type="button" aria-label="Следующая фотография">›</button><div class="guest-track">${files.map((f,i)=>`<div class="guest-slide"><img src="${asset(f)}" alt="Гости Ветратории — фото ${i+1}" loading="lazy"></div>`).join('')}</div><div class="guest-dots">${files.map((_,i)=>`<button class="guest-dot${i===0?' active':''}" type="button" aria-label="Фото ${i+1}" data-slide="${i}"></button>`).join('')}</div></div><div class="guest-footer"><p class="guest-quote">К нам приезжают гости, а уезжают друзья!</p><a href="https://t.me/wingfoil_center" class="guest-telegram" target="_blank" rel="noopener">Вступить в наш телеграм чат</a></div></section>`;
  const viewport=mount.querySelector('.guest-viewport'),track=mount.querySelector('.guest-track'),dots=[...mount.querySelectorAll('.guest-dot')];let index=0,timer,startX=0;
  const update=i=>{index=(i+files.length)%files.length;track.style.transform=`translateX(-${index*100}%)`;dots.forEach((d,n)=>d.classList.toggle('active',n===index));clearInterval(timer);timer=setInterval(()=>update(index+1),5000)};
  mount.querySelector('.guest-prev').addEventListener('click',()=>update(index-1));mount.querySelector('.guest-next').addEventListener('click',()=>update(index+1));dots.forEach(d=>d.addEventListener('click',()=>update(Number(d.dataset.slide))));viewport.addEventListener('touchstart',e=>startX=e.touches[0].clientX,{passive:true});viewport.addEventListener('touchend',e=>{const diff=startX-e.changedTouches[0].clientX;if(Math.abs(diff)>50)update(index+(diff>0?1:-1))},{passive:true});update(0);
})();
