(() => {
  const mount = document.getElementById('vf-organizers-root');
  if (!mount) return;
  const root = new URL('../', document.currentScript.src);
  const asset = name => new URL(`assets/organizers/${name}`, root).href;
  const logo = new URL('assets/en-footer-logo.webp', root).href;

  mount.innerHTML = `<section class="camp-hero" style="--camp-bg:url('${asset('hero.webp')}')"><div class="camp-overlay"></div><div class="camp-container"><div class="camp-brand"><img src="${asset('rrd.webp')}" alt="RRD"></div><div class="camp-content"><h1>Wingfoil camp for organizers</h1><p class="camp-text">For organizers of tours, camps, and wingfoil schools, we offer a unique partnership for unforgettable wingfoil camps in some of the best waters in the world, with top-of-the-line new wingfoil equipment from RRD.</p><p class="camp-text">Bring your students to Dahab and we will provide everything you need for their success and your thriving camp!</p><div class="camp-btns"><a class="camp-btn camp-btn--orange" href="https://drive.google.com/uc?export=download&id=1PK_M4dghrFlaM10TeW7ZT260RQwLB-gR" target="_blank" rel="noopener">Download PDF with conditions</a><a class="camp-btn" href="../#booking-form-en">Contact us</a></div></div></div></section><div class="camp-contact-modal" role="dialog" aria-modal="true" aria-labelledby="camp-contact-title"><div class="camp-contact-window"><button class="camp-contact-close" type="button" aria-label="Close">×</button><h2 id="camp-contact-title">Contact our manager</h2><a href="https://t.me/VetratoriaWingcenter" target="_blank" rel="noopener">Telegram: @VetratoriaWingcenter</a><a href="https://wa.me/201151015941" target="_blank" rel="noopener">WhatsApp: +20 115 101 5941</a></div></div><footer class="organizers-footer" id="contact"><div><img src="${logo}" alt="Vetratoria"><p>The site was developed by Egor Getsevich<br><a href="https://www.instagram.com/_gecevich_/">Instagram</a></p></div><div><h2>Follow Us</h2><a href="https://www.instagram.com/vetratoriaofficiale/">Instagram</a><br><a href="https://t.me/wingfoil_center">Telegram chat</a><p><b>WhatsApp:</b><br><a href="https://wa.me/201151015941">+20 115 101 5941</a><br><b>Telegram manager:</b><br><a href="https://t.me/VetratoriaWingcenter">@VetratoriaWingcenter</a><br><b>Email:</b><br>vetratoria.wingcenter@gmail.com</p></div></footer>`;
})();
