(() => {
  const mount = document.getElementById('vf-organizers-root');
  if (!mount) return;
  const root = new URL('../', document.currentScript.src);
  const asset = name => new URL(`assets/organizers/${name}`, root).href;
  const logo = new URL('assets/remaining/footer-logo.webp', root).href;

  mount.innerHTML = `<section class="camp-hero" style="--camp-bg:url('${asset('hero.webp')}')"><div class="camp-overlay"></div><div class="camp-container"><div class="camp-brand"><img src="${asset('rrd.webp')}" alt="RRD"></div><div class="camp-content"><h1>Для организаторов</h1><p class="camp-text">Наш центр предлагает уникальную площадку для проведения выездных школ по обучению парусному спорту:</p><div class="camp-classes"><p><span></span><b>Класс:</b> доска с крылом — вингфойлинг</p><p><span></span><b>Класс:</b> доска с парусом — виндсерфинг (см. сайт виндсерфинг-станции).</p></div><p class="camp-text">Привозите своих учеников в Дахаб — мы предоставим всё необходимое снаряжение: как учебное, так и продвинутое. Кроме того, к вашим услугам оборудованные площадки для проведения сборов и сопровождение лодкой на воде.</p><div class="camp-btns"><a class="camp-btn camp-btn--orange" href="https://drive.google.com/uc?export=download&id=1PK_M4dghrFlaM10TeW7ZT260RQwLB-gR" target="_blank" rel="noopener">Скачать ПДФ с условиями</a><a class="camp-btn" href="../ru/#booking-form">Связаться с нами</a></div></div></div></section><div class="camp-contact-modal" role="dialog" aria-modal="true" aria-labelledby="camp-contact-title"><div class="camp-contact-window"><button class="camp-contact-close" type="button" aria-label="Закрыть">×</button><h2 id="camp-contact-title">Связаться с менеджером</h2><a href="https://t.me/VetratoriaWingcenter" target="_blank" rel="noopener">Telegram: @VetratoriaWingcenter</a><a href="https://wa.me/201151015941" target="_blank" rel="noopener">WhatsApp: +20 115 101 5941</a></div></div><footer class="organizers-footer" id="contact"><div><img src="${logo}" alt="Ветратория"><p>Сайт разработал: Егор Гецевич<br><a href="https://www.instagram.com/_gecevich_/">Instagram</a></p></div><div><h2>Социальные сети</h2><a href="https://www.instagram.com/vetratoriaofficiale/">Инстаграм</a><br><a href="https://t.me/wingfoil_center">Телеграм-чат</a><p><b>WhatsApp:</b><br><a href="https://wa.me/201151015941">+20 115 101 5941</a><br><b>Telegram менеджера:</b><br><a href="https://t.me/VetratoriaWingcenter">@VetratoriaWingcenter</a><br><b>Почта:</b><br>vetratoria.wingcenter@gmail.com</p></div></footer>`;
})();
